### ISSUE TITLE
Config all systems on my own PC.

### ISSUE THREAD

**Issue by MiguelAngelCifredo** [sos-2016-02/sos-2016-02#5]
Configure all systems at my own PC with apps and pluggins with backlog instructions.

**Comment by Crileaech** [comment]
Una pregunta yo estoy usando openlabs por lo tanto instalarme sublime o node no lo he hecho pregunta es necesario ?? o una vez que trabajemos con ellos lo subo al repositorio que creemos en el github ???

**Comment by Crileaech** [comment]
Heroku no es para este martes es para el martes 1 de marzo, Habéis instalado Heroku y hecho Hola mundo como indicaba en el backlog ??

**Comment by tuxayo** [comment]
> lo tanto instalarme sublime o node no lo he hecho pregunta es necesario ??

- Es muy posible que te des cuenta que trabajar 100% en OpenLabs no es practico.
- Es importante de saber instalar un entorno de desarrollo.
- Sublime Text no es necesario, cualquier editor que puedas bien trabajar con.
  - Te recomendo de probar [Atom](https://atom.io/) porque
    - Es software libre
    - @MiguelAngelCifredo lo usa también y yo se usarlo.
- Es necesario instalar a Node (y saber hacer funcionar el hola mundo al menos)

**Comment by tuxayo** [comment]
> o una vez que trabajemos con ellos **lo** subo al repositorio que creemos en el github ???

Subir que? (a que te refieres por "lo")

**Comment by tuxayo** [comment]
> Habéis instalado Heroku y hecho Hola mundo como indicaba en el backlog ??

Tengo la Heroku toolbelt pero no he probado usarla con Heroku

Vocabulario para evitar confusión:
- Heroku: Un plataforma para desplegar aplicaciones web (a host provider)
- Heroku toolbelt: Una herramienta a instalar par poder desplegar y actualizar su aplicación con un par de comandos

**Comment by tuxayo** [comment]
Instalaste todo? Necesitas ayuda?
