### ISSUE TITLE
REST client: display JSON

### ISSUE THREAD

**Issue by tuxayo** [sos-2016-02/sos-2016-02#68]
Specs:
> Mostrar los datos JSON devueltos por el servidor

Si después de la tabla, añado los datos JSON es ok?

**Comment by MiguelAngelCifredo** [comment]
Creo que o Datos JSON o tabla, pero no ambas cosas a la vez.

**Comment by tuxayo** [comment]
Specs:
> Mostrar los datos JSON devueltos por el servidor

Pero como es solo en tu cliente y que el cliente del grupo cumple con eso, no es un problema.

**Comment by MiguelAngelCifredo** [comment]
Entonces perfecto. En el ClientRest de grupo SOLO datos JSON y, en el cada uno de nosotros SOLO datos en <table>
