### ISSUE TITLE
REST client: pretty print

### ISSUE THREAD

**Issue by tuxayo** [sos-2016-02/sos-2016-02#71]
Para el cliente REST probé eso (una lib y dos lineas de codigo), lo guardamos?

![screen shot 2016-04-16 at 13 50 47](https://cloud.githubusercontent.com/assets/2678215/14580805/4c067f7c-03da-11e6-85cf-669ec8f3d0ff.png)
![capture d ecran_2016-04-16_13-48-25](https://cloud.githubusercontent.com/assets/2678215/14580806/4faba6a2-03da-11e6-82c2-8eb270394194.png)

**Comment by MiguelAngelCifredo** [comment]
A pesar de lo bonito que queda y, además cono sólo 2 líneas de código, creo que no era eso a lo que se referían con "mostrar en modo tabla".
